version: 2

sphinx:
  builder: singlehtml
  configuration: doc/source/conf.py

formats: all

conda:
  environment: environment.yml

python:
  install:
    - path: .
    - requirements: doc/requirements-rtd.txt
