name: adaptivefiltering
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gdal
  - IPython=7.21.0
  - ipyvolume
  - ipywidgets<8
  - ipyleaflet
  - jupyter-resource-usage
  - jupyterlab
  - pdal=2.3.0
  - python-pdal=2.4.2
  - pip
  - pillow
  - pip:
    - Click
    - geodaisy
    - geojson
    - jsonmerge
    - jsonschema==3.2.0
    - pyrsistent
    - pytools
    - xdg
    - xmltodict
    - pyproj
