name: adaptivefiltering
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gdal
  - ipympl
  - IPython=7.21.0
  - ipyvolume
  - ipywidgets<8
  - jupyterlab
  - pdal=2.3.0
  - python-pdal=2.4.2
  - pip
  - pip:
    - Click
    - geodaisy
    - geojson
    - ipython_blocking
    - jsonmerge
    - jsonschema
    - matplotlib
    - pyrsistent
    - xdg
    - xmltodict