name: adaptivefiltering
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gdal
  - ipyvolume
  - ipywidgets<8
  - jupyterlab
  - pdal=2.3.0
  - python-pdal=2.4.2
  - pip
  - pip:
    - jsonschema
    - matplotlib
    - pyrsistent
    - xdg
