name: adaptivefiltering-rtd
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gdal
  - IPython=7.21.0
  - ipyleaflet
  - jsonschema=3.2.0
  - jupyter-resource-usage
  - jupyterlab
  - pdal=2.3.0
  - python-pdal=2.4.2
  - pip
  - pillow
  - pip:
    - adaptivefiltering-library
    - Click
    - geojson
    - ipyfilechooser
    - ipywidgets==8.0.0b1
    - ipywidgets-jsonschema
    - jsonmerge
    - pyrsistent
    - pytools
    - xdg
    - xmltodict
    - pyproj
    - m2r2
    - nbsphinx
    - nbsphinx-link
    - sphinx_lfs_content
    - xmltodict
    - pyproj
