# Note: The version pinning in this file is necessary to make the
#       conda environment solve not exceed the memory limitations
#       of readthedocs. They are aware of the situation and might
#       eventually improve it: https://blog.readthedocs.com/better-conda-support/
name: adaptivefiltering-rtd
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipympl=0.7.0
  - IPython=7.21.0
  - ipyvolume=0.6.0a8
  - ipywidgets=7.6.3
  - python-pdal=2.4.0
  - gdal=3.3.0
  - pip=21.1.3
  - pip:
    - Click
    - geodaisy
    - geojson
    - ipython_blocking
    - jsonmerge
    - jsonschema
    - m2r2
    - nbsphinx
    - nbsphinx-link
    - pyrsistent
    - sphinx_lfs_content
    - xdg
    - ipyleaflet
    - xmltodict
