name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  build-and-test:
    name: Testing on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Conda with Python ${{ matrix.python-version }}
      uses: s-weigand/setup-conda@v1

    - name: Install conda dependencies
      run: |
        conda env update -n base --file environment.yml

    - name: Install development dependencies
      run: |
        python -m pip install -r requirements-dev.txt

    - name: Install the filteradapt Python package
      run: |
        python -m pip install .

    - name: Run Python tests
      run: |
        python -m pytest --nbval-lax

  coverage:
    name: Coverage Testing
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Conda with Python ${{ matrix.python-version }}
      uses: s-weigand/setup-conda@v1

    - name: Install conda dependencies
      run: |
        conda env update -n base --file environment.yml

    - name: Install development dependencies
      run: |
        python -m pip install -r requirements-dev.txt

    - name: Run Python tests
      run: |
        python -m pytest --cov=./filteradapt --cov-report=xml

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
